### ISSUE TITLE
ReferenceError: path is not defined

### ISSUE THREAD

**Issue by melbardis** [rgreenjr/atom-elixir-formatter#23]
hi, just installed the latest 1.04 version (1.0.3 worked), and started to get the following error:

`
ReferenceError: path is not defined
    at Object.nearestFormatterConfig (file:///C:/Users/epm/.atom/packages/atom-elixir-formatter/lib/formatter.js:81:23)
    at Object.getCommandOptions (file:///C:/Users/epm/.atom/packages/atom-elixir-formatter/lib/formatter.js:68:26)
    at Object.runFormat (file:///C:/Users/epm/.atom/packages/atom-elixir-formatter/lib/formatter.js:53:24)
    at Object.formatTextEditor (file:///C:/Users/epm/.atom/packages/atom-elixir-formatter/lib/formatter.js:28:54)
    at Object.formatActiveTextEditor (file:///C:/Users/epm/.atom/packages/atom-elixir-formatter/lib/formatter.js:15:14)
    at HTMLElement.atomElixirFormatterFormat (file:///C:/Users/epm/.atom/packages/atom-elixir-formatter/lib/main.js:23:57)
    at CommandRegistry.handleCommandEvent (C:\Users\epm\AppData\Local\atom\app-1.30.0\resources\app\src\command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\epm\AppData\Local\atom\app-1.30.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\epm\AppData\Local\atom\app-1.30.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (C:\Users\epm\AppData\Local\atom\app-1.30.0\resources\app\src\window-event-handler.js:110:40)
`

i added "import path from "path";" to formater.js and it works again ...

**Comment by rgreenjr** [comment]
Great catch, thanks! I just published version 1.0.5 with the missing import added.
