### ISSUE TITLE
Race conditions and formatting error

### ISSUE THREAD

**Issue by lukaszsamson** [rgreenjr/atom-elixir-formatter#3]
Env: macOS 10.13

When opening a file and saving it quickly the formatting sometimes fails with:
```
/var/folders/5t/z9kkxlhn4w769jqmn00xqqkw0000gn/T/tmp-55821I1xgZTTwJpb8
** (SyntaxError) /var/folders/5t/z9kkxlhn4w769jqmn00xqqkw0000gn/T/tmp-55821I1xgZTTwJpb8:1: syntax error before: b6f75
    (elixir) lib/code.ex:370: Code.format_string!/2
    (mix) lib/mix/tasks/format.ex:148: Mix.Tasks.Format.format_file/4
    (elixir) lib/enum.ex:1900: Enum."-reduce/3-lists^foldl/2-0-"/3
    (mix) lib/mix/tasks/format.ex:84: Mix.Tasks.Format.run/1
    (mix) lib/mix/task.ex:315: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:80: Mix.CLI.run_task/2
```
When I retry, it then succeeds.
Apparently the file is not yet completely copied to the temp dir when format is attempted.

**Comment by lukaszsamson** [comment]
It turned out to be caused by atom remembering selection in certain files.
